import { Code, Brain, ShoppingCart, WorkflowIcon as Wordpress, Video, Palette, TrendingUp } from "lucide-react"
import type { TechCategory } from "@/types/Technology"

export const techCategories: TechCategory[] = [
  {
    id: "web",
    title: "Web Development",
    icon: Code,
    description: "Modern frameworks and tools for building scalable web applications",
    gradient: "from-[#00D1FF]/20 to-[#0099CC]/20",
    count: 12,
    technologies: [
      {
        name: "React.js",
        icon: "⚛️",
        color: "#61DAFB",
        proficiency: 95,
        experience: "5+ years",
        description: "A JavaScript library for building user interfaces with component-based architecture",
        projects: 150,
        website: "https://reactjs.org",
        category: "web",
      },
      {
        name: "Next.js",
        icon: "▲",
        color: "#000000",
        proficiency: 92,
        experience: "4+ years",
        description: "The React framework for production with server-side rendering and static generation",
        projects: 120,
        website: "https://nextjs.org",
        category: "web",
      },
      {
        name: "TypeScript",
        icon: "📘",
        color: "#3178C6",
        proficiency: 90,
        experience: "4+ years",
        description: "Typed superset of JavaScript that compiles to plain JavaScript",
        projects: 200,
        website: "https://typescriptlang.org",
        category: "web",
      },
      {
        name: "Node.js",
        icon: "🟢",
        color: "#339933",
        proficiency: 88,
        experience: "5+ years",
        description: "JavaScript runtime built on Chrome's V8 JavaScript engine",
        projects: 180,
        website: "https://nodejs.org",
        category: "web",
      },
      {
        name: "Express.js",
        icon: "🚀",
        color: "#000000",
        proficiency: 85,
        experience: "4+ years",
        description: "Fast, unopinionated, minimalist web framework for Node.js",
        projects: 100,
        website: "https://expressjs.com",
        category: "web",
      },
      {
        name: "Tailwind CSS",
        icon: "💨",
        color: "#06B6D4",
        proficiency: 93,
        experience: "3+ years",
        description: "Utility-first CSS framework for rapidly building custom designs",
        projects: 160,
        website: "https://tailwindcss.com",
        category: "web",
      },
      {
        name: "Vue.js",
        icon: "💚",
        color: "#4FC08D",
        proficiency: 82,
        experience: "3+ years",
        description: "Progressive JavaScript framework for building user interfaces",
        projects: 80,
        website: "https://vuejs.org",
        category: "web",
      },
      {
        name: "Angular",
        icon: "🅰️",
        color: "#DD0031",
        proficiency: 78,
        experience: "3+ years",
        description: "Platform for building mobile and desktop web applications",
        projects: 60,
        website: "https://angular.io",
        category: "web",
      },
      {
        name: "Svelte",
        icon: "🧡",
        color: "#FF3E00",
        proficiency: 75,
        experience: "2+ years",
        description: "Cybernetically enhanced web apps with compile-time optimizations",
        projects: 40,
        website: "https://svelte.dev",
        category: "web",
      },
      {
        name: "GraphQL",
        icon: "🔗",
        color: "#E10098",
        proficiency: 80,
        experience: "3+ years",
        description: "Query language for APIs and runtime for executing queries",
        projects: 70,
        website: "https://graphql.org",
        category: "web",
      },
      {
        name: "MongoDB",
        icon: "🍃",
        color: "#47A248",
        proficiency: 85,
        experience: "4+ years",
        description: "Document-oriented NoSQL database program",
        projects: 90,
        website: "https://mongodb.com",
        category: "web",
      },
      {
        name: "PostgreSQL",
        icon: "🐘",
        color: "#336791",
        proficiency: 83,
        experience: "4+ years",
        description: "Advanced open source relational database",
        projects: 85,
        website: "https://postgresql.org",
        category: "web",
      },
    ],
  },
  {
    id: "ai",
    title: "AI & Machine Learning",
    icon: Brain,
    description: "Cutting-edge artificial intelligence and machine learning technologies",
    gradient: "from-[#FF6B6B]/20 to-[#FF8E53]/20",
    count: 10,
    technologies: [
      {
        name: "Python",
        icon: "🐍",
        color: "#3776AB",
        proficiency: 94,
        experience: "6+ years",
        description: "High-level programming language perfect for AI and data science",
        projects: 200,
        website: "https://python.org",
        category: "ai",
      },
      {
        name: "TensorFlow",
        icon: "🧠",
        color: "#FF6F00",
        proficiency: 88,
        experience: "4+ years",
        description: "End-to-end open source platform for machine learning",
        projects: 80,
        website: "https://tensorflow.org",
        category: "ai",
      },
      {
        name: "PyTorch",
        icon: "🔥",
        color: "#EE4C2C",
        proficiency: 85,
        experience: "3+ years",
        description: "Open source machine learning library based on Torch",
        projects: 70,
        website: "https://pytorch.org",
        category: "ai",
      },
      {
        name: "OpenAI GPT",
        icon: "🤖",
        color: "#412991",
        proficiency: 90,
        experience: "2+ years",
        description: "Advanced language models for natural language processing",
        projects: 60,
        website: "https://openai.com",
        category: "ai",
      },
      {
        name: "Hugging Face",
        icon: "🤗",
        color: "#FFD21E",
        proficiency: 87,
        experience: "2+ years",
        description: "Platform for machine learning models and datasets",
        projects: 50,
        website: "https://huggingface.co",
        category: "ai",
      },
      {
        name: "LangChain",
        icon: "🔗",
        color: "#1C3A3A",
        proficiency: 82,
        experience: "1+ years",
        description: "Framework for developing applications powered by language models",
        projects: 40,
        website: "https://langchain.com",
        category: "ai",
      },
      {
        name: "Scikit-learn",
        icon: "📊",
        color: "#F7931E",
        proficiency: 86,
        experience: "4+ years",
        description: "Machine learning library for Python",
        projects: 90,
        website: "https://scikit-learn.org",
        category: "ai",
      },
      {
        name: "Pandas",
        icon: "🐼",
        color: "#150458",
        proficiency: 91,
        experience: "5+ years",
        description: "Data manipulation and analysis library for Python",
        projects: 120,
        website: "https://pandas.pydata.org",
        category: "ai",
      },
      {
        name: "NumPy",
        icon: "🔢",
        color: "#013243",
        proficiency: 89,
        experience: "5+ years",
        description: "Fundamental package for scientific computing with Python",
        projects: 150,
        website: "https://numpy.org",
        category: "ai",
      },
      {
        name: "Jupyter",
        icon: "📓",
        color: "#F37626",
        proficiency: 85,
        experience: "4+ years",
        description: "Interactive computing environment for data science",
        projects: 100,
        website: "https://jupyter.org",
        category: "ai",
      },
    ],
  },
  {
    id: "ecommerce",
    title: "E-Commerce Solutions",
    icon: ShoppingCart,
    description: "Comprehensive solutions for online stores and payment processing",
    gradient: "from-[#4ECDC4]/20 to-[#44A08D]/20",
    count: 8,
    technologies: [
      {
        name: "Shopify",
        icon: "🛍️",
        color: "#7AB55C",
        proficiency: 92,
        experience: "4+ years",
        description: "Leading e-commerce platform for online stores",
        projects: 100,
        website: "https://shopify.com",
        category: "ecommerce",
      },
      {
        name: "WooCommerce",
        icon: "🛒",
        color: "#96588A",
        proficiency: 89,
        experience: "5+ years",
        description: "WordPress e-commerce plugin for online selling",
        projects: 120,
        website: "https://woocommerce.com",
        category: "ecommerce",
      },
      {
        name: "Magento",
        icon: "🏪",
        color: "#EE672F",
        proficiency: 78,
        experience: "3+ years",
        description: "Open-source e-commerce platform for large businesses",
        projects: 40,
        website: "https://magento.com",
        category: "ecommerce",
      },
      {
        name: "Stripe",
        icon: "💳",
        color: "#635BFF",
        proficiency: 94,
        experience: "4+ years",
        description: "Online payment processing for internet businesses",
        projects: 150,
        website: "https://stripe.com",
        category: "ecommerce",
      },
      {
        name: "PayPal",
        icon: "💰",
        color: "#00457C",
        proficiency: 88,
        experience: "5+ years",
        description: "Digital payment platform for online transactions",
        projects: 130,
        website: "https://paypal.com",
        category: "ecommerce",
      },
      {
        name: "BigCommerce",
        icon: "🏬",
        color: "#121118",
        proficiency: 75,
        experience: "2+ years",
        description: "SaaS e-commerce platform for growing businesses",
        projects: 30,
        website: "https://bigcommerce.com",
        category: "ecommerce",
      },
      {
        name: "Square",
        icon: "⬜",
        color: "#3E4348",
        proficiency: 80,
        experience: "3+ years",
        description: "Payment processing and point-of-sale solutions",
        projects: 60,
        website: "https://squareup.com",
        category: "ecommerce",
      },
      {
        name: "Klarna",
        icon: "💎",
        color: "#FFB3C7",
        proficiency: 72,
        experience: "2+ years",
        description: "Buy now, pay later payment solutions",
        projects: 25,
        website: "https://klarna.com",
        category: "ecommerce",
      },
    ],
  },
  {
    id: "wordpress",
    title: "WordPress Ecosystem",
    icon: Wordpress,
    description: "Powerful WordPress development and customization tools",
    gradient: "from-[#667eea]/20 to-[#764ba2]/20",
    count: 8,
    technologies: [
      {
        name: "WordPress",
        icon: "📝",
        color: "#21759B",
        proficiency: 95,
        experience: "6+ years",
        description: "World's most popular content management system",
        projects: 200,
        website: "https://wordpress.org",
        category: "wordpress",
      },
      {
        name: "Elementor",
        icon: "🏗️",
        color: "#92003B",
        proficiency: 90,
        experience: "4+ years",
        description: "Leading WordPress page builder plugin",
        projects: 150,
        website: "https://elementor.com",
        category: "wordpress",
      },
      {
        name: "WPBakery",
        icon: "🧱",
        color: "#00A0D2",
        proficiency: 85,
        experience: "4+ years",
        description: "Drag and drop page builder for WordPress",
        projects: 100,
        website: "https://wpbakery.com",
        category: "wordpress",
      },
      {
        name: "ACF Pro",
        icon: "🔧",
        color: "#00A0D2",
        proficiency: 92,
        experience: "5+ years",
        description: "Advanced Custom Fields for WordPress development",
        projects: 180,
        website: "https://advancedcustomfields.com",
        category: "wordpress",
      },
      {
        name: "Yoast SEO",
        icon: "📊",
        color: "#A4286A",
        proficiency: 88,
        experience: "5+ years",
        description: "WordPress SEO plugin for better search rankings",
        projects: 160,
        website: "https://yoast.com",
        category: "wordpress",
      },
      {
        name: "Wordfence",
        icon: "🛡️",
        color: "#00709E",
        proficiency: 83,
        experience: "4+ years",
        description: "WordPress security plugin for malware protection",
        projects: 140,
        website: "https://wordfence.com",
        category: "wordpress",
      },
      {
        name: "Gutenberg",
        icon: "📄",
        color: "#0073AA",
        proficiency: 87,
        experience: "3+ years",
        description: "WordPress block editor for content creation",
        projects: 120,
        website: "https://wordpress.org/gutenberg",
        category: "wordpress",
      },
      {
        name: "WP Rocket",
        icon: "🚀",
        color: "#F56640",
        proficiency: 85,
        experience: "3+ years",
        description: "WordPress caching plugin for performance optimization",
        projects: 100,
        website: "https://wp-rocket.me",
        category: "wordpress",
      },
    ],
  },
  {
    id: "video",
    title: "Video Production",
    icon: Video,
    description: "Professional video editing and motion graphics software",
    gradient: "from-[#f093fb]/20 to-[#f5576c]/20",
    count: 6,
    technologies: [
      {
        name: "Adobe Premiere Pro",
        icon: "🎬",
        color: "#9999FF",
        proficiency: 88,
        experience: "4+ years",
        description: "Industry-standard video editing software",
        projects: 80,
        website: "https://adobe.com/premiere",
        category: "video",
      },
      {
        name: "After Effects",
        icon: "✨",
        color: "#9999FF",
        proficiency: 85,
        experience: "4+ years",
        description: "Motion graphics and visual effects software",
        projects: 70,
        website: "https://adobe.com/aftereffects",
        category: "video",
      },
      {
        name: "Final Cut Pro",
        icon: "🎞️",
        color: "#000000",
        proficiency: 82,
        experience: "3+ years",
        description: "Professional video editing for Mac",
        projects: 60,
        website: "https://apple.com/final-cut-pro",
        category: "video",
      },
      {
        name: "DaVinci Resolve",
        icon: "🎨",
        color: "#233A51",
        proficiency: 78,
        experience: "2+ years",
        description: "Professional color grading and video editing",
        projects: 40,
        website: "https://blackmagicdesign.com/davinci",
        category: "video",
      },
      {
        name: "Cinema 4D",
        icon: "🎭",
        color: "#011A6A",
        proficiency: 75,
        experience: "2+ years",
        description: "3D modeling and animation software",
        projects: 30,
        website: "https://maxon.net/cinema-4d",
        category: "video",
      },
      {
        name: "Blender",
        icon: "🌀",
        color: "#F5792A",
        proficiency: 72,
        experience: "2+ years",
        description: "Open-source 3D creation suite",
        projects: 25,
        website: "https://blender.org",
        category: "video",
      },
    ],
  },
  {
    id: "design",
    title: "Creative Design",
    icon: Palette,
    description: "Creative design tools for stunning visual experiences",
    gradient: "from-[#a8edea]/20 to-[#fed6e3]/20",
    count: 7,
    technologies: [
      {
        name: "Figma",
        icon: "🎯",
        color: "#F24E1E",
        proficiency: 95,
        experience: "4+ years",
        description: "Collaborative interface design tool",
        projects: 200,
        website: "https://figma.com",
        category: "design",
      },
      {
        name: "Adobe Photoshop",
        icon: "🖼️",
        color: "#31A8FF",
        proficiency: 92,
        experience: "6+ years",
        description: "Industry-standard image editing software",
        projects: 250,
        website: "https://adobe.com/photoshop",
        category: "design",
      },
      {
        name: "Adobe Illustrator",
        icon: "🎨",
        color: "#FF9A00",
        proficiency: 89,
        experience: "5+ years",
        description: "Vector graphics and illustration software",
        projects: 180,
        website: "https://adobe.com/illustrator",
        category: "design",
      },
      {
        name: "Adobe XD",
        icon: "💎",
        color: "#FF61F6",
        proficiency: 85,
        experience: "3+ years",
        description: "UX/UI design and prototyping tool",
        projects: 120,
        website: "https://adobe.com/xd",
        category: "design",
      },
      {
        name: "Sketch",
        icon: "💠",
        color: "#F7B500",
        proficiency: 80,
        experience: "3+ years",
        description: "Digital design toolkit for Mac",
        projects: 90,
        website: "https://sketch.com",
        category: "design",
      },
      {
        name: "Canva",
        icon: "📐",
        color: "#00C4CC",
        proficiency: 88,
        experience: "3+ years",
        description: "Graphic design platform for everyone",
        projects: 150,
        website: "https://canva.com",
        category: "design",
      },
      {
        name: "InVision",
        icon: "👁️",
        color: "#FF3366",
        proficiency: 78,
        experience: "2+ years",
        description: "Digital product design platform",
        projects: 60,
        website: "https://invisionapp.com",
        category: "design",
      },
    ],
  },
  {
    id: "seo",
    title: "SEO & Analytics",
    icon: TrendingUp,
    description: "Advanced SEO tools and analytics for digital marketing success",
    gradient: "from-[#ffecd2]/20 to-[#fcb69f]/20",
    count: 8,
    technologies: [
      {
        name: "Google Analytics",
        icon: "📈",
        color: "#E37400",
        proficiency: 93,
        experience: "5+ years",
        description: "Web analytics service for tracking website traffic",
        projects: 180,
        website: "https://analytics.google.com",
        category: "seo",
      },
      {
        name: "Google Search Console",
        icon: "🔍",
        color: "#4285F4",
        proficiency: 91,
        experience: "5+ years",
        description: "Monitor and troubleshoot website presence in Google Search",
        projects: 170,
        website: "https://search.google.com/search-console",
        category: "seo",
      },
      {
        name: "Ahrefs",
        icon: "🔗",
        color: "#FF7A00",
        proficiency: 88,
        experience: "4+ years",
        description: "SEO toolset for backlink analysis and keyword research",
        projects: 100,
        website: "https://ahrefs.com",
        category: "seo",
      },
      {
        name: "SEMrush",
        icon: "📊",
        color: "#FF642D",
        proficiency: 85,
        experience: "4+ years",
        description: "All-in-one digital marketing toolkit",
        projects: 90,
        website: "https://semrush.com",
        category: "seo",
      },
      {
        name: "Moz Pro",
        icon: "🦎",
        color: "#004C91",
        proficiency: 82,
        experience: "3+ years",
        description: "SEO software suite for better search rankings",
        projects: 70,
        website: "https://moz.com",
        category: "seo",
      },
      {
        name: "Screaming Frog",
        icon: "🐸",
        color: "#8CC152",
        proficiency: 80,
        experience: "3+ years",
        description: "Website crawler for technical SEO audits",
        projects: 80,
        website: "https://screamingfrog.co.uk",
        category: "seo",
      },
      {
        name: "Hotjar",
        icon: "🔥",
        color: "#FD3A69",
        proficiency: 78,
        experience: "2+ years",
        description: "Behavior analytics and user feedback tool",
        projects: 60,
        website: "https://hotjar.com",
        category: "seo",
      },
      {
        name: "GTM",
        icon: "🏷️",
        color: "#4285F4",
        proficiency: 85,
        experience: "3+ years",
        description: "Google Tag Manager for tracking code management",
        projects: 120,
        website: "https://tagmanager.google.com",
        category: "seo",
      },
    ],
  },
]
